import type { WorkloadProfile } from "@/lib/core/types";

export const workloadProfiles: Record<WorkloadProfile["id"], WorkloadProfile> = {
  esports_competitive: {
    id: "esports_competitive",
    label: "Esport / competitive",
    defaultResolution: "1080p",
    defaultTargetFps: 240,
    cpuWeight: 0.34,
    gpuWeight: 0.28,
    ramWeight: 0.14,
    storageWeight: 0.06,
    rayTracingWeight: 0.02,
    streamingWeight: 0.04,
    productivityWeight: 0.02,
    longevityWeight: 0.1,
  },
  shooter_high_fps: {
    id: "shooter_high_fps",
    label: "Shootery high FPS",
    defaultResolution: "1080p",
    defaultTargetFps: 165,
    cpuWeight: 0.3,
    gpuWeight: 0.34,
    ramWeight: 0.12,
    storageWeight: 0.06,
    rayTracingWeight: 0.03,
    streamingWeight: 0.05,
    productivityWeight: 0.02,
    longevityWeight: 0.08,
  },
  aaa_visual: {
    id: "aaa_visual",
    label: "AAA / wizualne",
    defaultResolution: "1440p",
    defaultTargetFps: 90,
    cpuWeight: 0.18,
    gpuWeight: 0.46,
    ramWeight: 0.1,
    storageWeight: 0.08,
    rayTracingWeight: 0.08,
    streamingWeight: 0.02,
    productivityWeight: 0.0,
    longevityWeight: 0.08,
  },
  story_visual: {
    id: "story_visual",
    label: "Single player / story",
    defaultResolution: "1440p",
    defaultTargetFps: 60,
    cpuWeight: 0.2,
    gpuWeight: 0.42,
    ramWeight: 0.1,
    storageWeight: 0.1,
    rayTracingWeight: 0.07,
    streamingWeight: 0.01,
    productivityWeight: 0.0,
    longevityWeight: 0.1,
  },
  mixed_gaming: {
    id: "mixed_gaming",
    label: "Gaming mieszany",
    defaultResolution: "1080p",
    defaultTargetFps: 120,
    cpuWeight: 0.24,
    gpuWeight: 0.38,
    ramWeight: 0.11,
    storageWeight: 0.08,
    rayTracingWeight: 0.05,
    streamingWeight: 0.04,
    productivityWeight: 0.02,
    longevityWeight: 0.08,
  },
  gaming_plus_streaming: {
    id: "gaming_plus_streaming",
    label: "Gaming + streaming",
    defaultResolution: "1080p",
    defaultTargetFps: 144,
    cpuWeight: 0.24,
    gpuWeight: 0.34,
    ramWeight: 0.12,
    storageWeight: 0.06,
    rayTracingWeight: 0.03,
    streamingWeight: 0.14,
    productivityWeight: 0.01,
    longevityWeight: 0.06,
  },
  gaming_plus_productivity: {
    id: "gaming_plus_productivity",
    label: "Gaming + praca",
    defaultResolution: "1440p",
    defaultTargetFps: 100,
    cpuWeight: 0.28,
    gpuWeight: 0.3,
    ramWeight: 0.12,
    storageWeight: 0.08,
    rayTracingWeight: 0.03,
    streamingWeight: 0.05,
    productivityWeight: 0.08,
    longevityWeight: 0.06,
  },
  creator_light: {
    id: "creator_light",
    label: "Lekka kreatywna praca",
    defaultResolution: "1080p",
    defaultTargetFps: 60,
    cpuWeight: 0.28,
    gpuWeight: 0.24,
    ramWeight: 0.14,
    storageWeight: 0.12,
    rayTracingWeight: 0.01,
    streamingWeight: 0.03,
    productivityWeight: 0.12,
    longevityWeight: 0.06,
  },
  creator_heavy: {
    id: "creator_heavy",
    label: "Cięższa praca kreatywna",
    defaultResolution: "1440p",
    defaultTargetFps: 60,
    cpuWeight: 0.32,
    gpuWeight: 0.22,
    ramWeight: 0.16,
    storageWeight: 0.14,
    rayTracingWeight: 0.0,
    streamingWeight: 0.02,
    productivityWeight: 0.1,
    longevityWeight: 0.04,
  },
};
