import type { GpuRecord } from "@/lib/core/types";

const SOURCE = "KOMPBRAT local curated baseline v1";
const SOURCE_URL = "https://kompbrat.local/gpu-db";
const UPDATED_AT = "2026-04-06";

export const gpuDb: GpuRecord[] = [
  {
    id: "intel-arc-b580",
    type: "gpu",
    name: "Intel Arc B580 12 GB",
    aliases: ["b580", "arc b580", "intel arc b580"],
    vendor: "Intel",
    vramGb: 12,
    raster1080p: 78,
    raster1440p: 70,
    raster4k: 42,
    rtScore: 46,
    powerW: 190,
    dlss: false,
    fsr: true,
    nvenc: false,
    cuda: false,
    av1Encode: true,
    usedPricePln: null,
    newPricePln: 1180,
    source: SOURCE,
    sourceUrl: SOURCE_URL,
    updatedAt: UPDATED_AT,
  },
  {
    id: "amd-radeon-rx-6600",
    type: "gpu",
    name: "AMD Radeon RX 6600 8 GB",
    aliases: ["rx 6600", "rx6600", "6600"],
    vendor: "AMD",
    vramGb: 8,
    raster1080p: 64,
    raster1440p: 48,
    raster4k: 26,
    rtScore: 24,
    powerW: 132,
    dlss: false,
    fsr: true,
    nvenc: false,
    cuda: false,
    av1Encode: false,
    usedPricePln: 650,
    newPricePln: 930,
    source: SOURCE,
    sourceUrl: SOURCE_URL,
    updatedAt: UPDATED_AT,
  },
  {
    id: "amd-radeon-rx-6650-xt",
    type: "gpu",
    name: "AMD Radeon RX 6650 XT 8 GB",
    aliases: ["rx 6650 xt", "rx6650xt", "6650 xt"],
    vendor: "AMD",
    vramGb: 8,
    raster1080p: 75,
    raster1440p: 56,
    raster4k: 30,
    rtScore: 28,
    powerW: 180,
    dlss: false,
    fsr: true,
    nvenc: false,
    cuda: false,
    av1Encode: false,
    usedPricePln: 820,
    newPricePln: 1090,
    source: SOURCE,
    sourceUrl: SOURCE_URL,
    updatedAt: UPDATED_AT,
  },
  {
    id: "amd-radeon-rx-6700-xt",
    type: "gpu",
    name: "AMD Radeon RX 6700 XT 12 GB",
    aliases: ["rx 6700 xt", "rx6700xt", "6700 xt"],
    vendor: "AMD",
    vramGb: 12,
    raster1080p: 88,
    raster1440p: 72,
    raster4k: 40,
    rtScore: 34,
    powerW: 230,
    dlss: false,
    fsr: true,
    nvenc: false,
    cuda: false,
    av1Encode: false,
    usedPricePln: 1150,
    newPricePln: null,
    source: SOURCE,
    sourceUrl: SOURCE_URL,
    updatedAt: UPDATED_AT,
  },
  {
    id: "amd-radeon-rx-6800-xt",
    type: "gpu",
    name: "AMD Radeon RX 6800 XT 16 GB",
    aliases: ["rx 6800 xt", "rx6800xt", "6800 xt"],
    vendor: "AMD",
    vramGb: 16,
    raster1080p: 100,
    raster1440p: 88,
    raster4k: 60,
    rtScore: 42,
    powerW: 300,
    dlss: false,
    fsr: true,
    nvenc: false,
    cuda: false,
    av1Encode: false,
    usedPricePln: 1750,
    newPricePln: null,
    source: SOURCE,
    sourceUrl: SOURCE_URL,
    updatedAt: UPDATED_AT,
  },
  {
    id: "amd-radeon-rx-7600",
    type: "gpu",
    name: "AMD Radeon RX 7600 8 GB",
    aliases: ["rx 7600", "rx7600", "7600"],
    vendor: "AMD",
    vramGb: 8,
    raster1080p: 72,
    raster1440p: 54,
    raster4k: 30,
    rtScore: 28,
    powerW: 165,
    dlss: false,
    fsr: true,
    nvenc: false,
    cuda: false,
    av1Encode: true,
    usedPricePln: 900,
    newPricePln: 1120,
    source: SOURCE,
    sourceUrl: SOURCE_URL,
    updatedAt: UPDATED_AT,
  },
  {
    id: "amd-radeon-rx-7700-xt",
    type: "gpu",
    name: "AMD Radeon RX 7700 XT 12 GB",
    aliases: ["rx 7700 xt", "rx7700xt", "7700 xt"],
    vendor: "AMD",
    vramGb: 12,
    raster1080p: 94,
    raster1440p: 80,
    raster4k: 48,
    rtScore: 42,
    powerW: 245,
    dlss: false,
    fsr: true,
    nvenc: false,
    cuda: false,
    av1Encode: true,
    usedPricePln: 1650,
    newPricePln: 1990,
    source: SOURCE,
    sourceUrl: SOURCE_URL,
    updatedAt: UPDATED_AT,
  },
  {
    id: "nvidia-geforce-rtx-3060-12gb",
    type: "gpu",
    name: "NVIDIA GeForce RTX 3060 12 GB",
    aliases: ["rtx 3060", "rtx3060", "3060 12gb", "rtx 3060 12gb"],
    vendor: "NVIDIA",
    vramGb: 12,
    raster1080p: 70,
    raster1440p: 54,
    raster4k: 28,
    rtScore: 35,
    powerW: 170,
    dlss: true,
    fsr: true,
    nvenc: true,
    cuda: true,
    av1Encode: false,
    usedPricePln: 950,
    newPricePln: null,
    source: SOURCE,
    sourceUrl: SOURCE_URL,
    updatedAt: UPDATED_AT,
  },
  {
    id: "nvidia-geforce-rtx-3070",
    type: "gpu",
    name: "NVIDIA GeForce RTX 3070 8 GB",
    aliases: ["rtx 3070", "rtx3070", "3070"],
    vendor: "NVIDIA",
    vramGb: 8,
    raster1080p: 92,
    raster1440p: 78,
    raster4k: 46,
    rtScore: 52,
    powerW: 220,
    dlss: true,
    fsr: true,
    nvenc: true,
    cuda: true,
    av1Encode: false,
    usedPricePln: 1450,
    newPricePln: null,
    source: SOURCE,
    sourceUrl: SOURCE_URL,
    updatedAt: UPDATED_AT,
  },
  {
    id: "nvidia-geforce-rtx-3080-10gb",
    type: "gpu",
    name: "NVIDIA GeForce RTX 3080 10 GB",
    aliases: ["rtx 3080", "rtx3080", "3080 10gb", "rtx 3080 10gb"],
    vendor: "NVIDIA",
    vramGb: 10,
    raster1080p: 98,
    raster1440p: 86,
    raster4k: 58,
    rtScore: 72,
    powerW: 320,
    dlss: true,
    fsr: true,
    nvenc: true,
    cuda: true,
    av1Encode: false,
    usedPricePln: 1850,
    newPricePln: null,
    source: SOURCE,
    sourceUrl: SOURCE_URL,
    updatedAt: UPDATED_AT,
  },
  {
    id: "nvidia-geforce-rtx-4060",
    type: "gpu",
    name: "NVIDIA GeForce RTX 4060 8 GB",
    aliases: ["rtx 4060", "rtx4060", "4060"],
    vendor: "NVIDIA",
    vramGb: 8,
    raster1080p: 76,
    raster1440p: 58,
    raster4k: 32,
    rtScore: 46,
    powerW: 115,
    dlss: true,
    fsr: true,
    nvenc: true,
    cuda: true,
    av1Encode: true,
    usedPricePln: 1100,
    newPricePln: 1390,
    source: SOURCE,
    sourceUrl: SOURCE_URL,
    updatedAt: UPDATED_AT,
  },
  {
    id: "nvidia-geforce-rtx-4060-ti-8gb",
    type: "gpu",
    name: "NVIDIA GeForce RTX 4060 Ti 8 GB",
    aliases: ["rtx 4060 ti", "rtx4060ti", "4060ti"],
    vendor: "NVIDIA",
    vramGb: 8,
    raster1080p: 90,
    raster1440p: 72,
    raster4k: 40,
    rtScore: 58,
    powerW: 160,
    dlss: true,
    fsr: true,
    nvenc: true,
    cuda: true,
    av1Encode: true,
    usedPricePln: 1450,
    newPricePln: 1780,
    source: SOURCE,
    sourceUrl: SOURCE_URL,
    updatedAt: UPDATED_AT,
  },
];

export function getGpuPrice(gpu: GpuRecord, condition: "new" | "used") {
  return condition === "used" ? gpu.usedPricePln : gpu.newPricePln;
}
